### ISSUE TITLE
quda 0.7.0  milc-interface 

### ISSUE THREAD

**Issue by lcosmai** [lattice/milc-interface#1]
After having built quda 0.7.0, I tried to install milc-interface.
I put the entire "milc_inteface" directory in the quda-0.7.0 top-level directory and then in this milc_interface directory I run "make all".
I got the following error message:
milc_init_finalize_interface.cpp:86:29: error: hisq_force_quda.h: No such file or directory
milc_init_finalize_interface.cpp: In function 'void qudaHisqParamsInit(QudaHisqParams_t)':
milc_init_finalize_interface.cpp:109: error: 'quda::fermion_force' has not been declared
make: *** [milc_init_finalize_interface.o] Error 1

**Comment by mathiaswagner** [comment]
The separate MILC interface is no longer needed. Just build QUDA with the MILC interface enabled in the configure step.
